name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fzarifian/x2go:build

      - name: Authenticate to quay.io
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} quay.io
        if: github.event_name == 'push'

      - name: Push to quay.io
        run: |
          docker tag fzarifian/x2go:build quay.io/fzarifian/x2go:latest
          docker push quay.io/fzarifian/x2go:latest
        if: github.event_name == 'push'
        
      - name: Authenticate to docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        if: github.event_name == 'push'
        
      - name: Push to docker hub
        run: |
          docker tag fzarifian/x2go:build fzarifian/x2go:latest 
          docker push fzarifian/x2go:latest
        if: github.event_name == 'push'

      - name: Authenticate to github packages
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        if: github.event_name == 'push'
  
      - name: Push to github packages
        run: |
          docker tag fzarifian/x2go:build docker.pkg.github.com/fzarifian/docker-x2go/centos:latest
          docker push docker.pkg.github.com/fzarifian/docker-x2go/centos:latest
        if: github.event_name == 'push'
